[General]
bMaxPayne2=1
; game installation directory (must include a backslash)
sGameDir="C:\Program Files\Steam\steamapps\common\Max Payne 2\"
iWidth=2560
iHeight=1440
; mod name (without the extension)
sModName=""
bUnlockAllDiff=0
bUnlockAllChapters=0
; launch parameters (see https://www.pcgamingwiki.com/wiki/Max_Payne_2:_The_Fall_of_Max_Payne#Command_line_arguments for details)
bDeveloper=0
bDeveloperKeys=0
bDisable3dpreloads=0
bNodialog=0
bNovidmemcheck=0
bProfile=0
bSkipstartup=0
bScreenshot=0
bShowprogress=0
bWindow=0
; skip the GUI and directly run the game with the values above
bNoGUI=0

