[General]
; game installation directory
sGameDir="C:\Program Files\Steam\steamapps\common\Max Payne 2\"
nWidth=2560
nHeight=1440
; mod name (without the .mp2m extension)
sModName=""
bUnlockAllDiff=1
bUnlockAllChapters=1
; skip the GUI and directly run the game with the values above
bNoGUI=0